
name: bild_yml

on:
  push:
    branches:
      - main

jobs: 
 first_j: 
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
