
name: bild_yml
env:
  file_name: artifact_body.txt
  path: ./
  artifact_name: artifact_1

on:
  push:
    branches:
      - main

jobs: 
 first_j: 
  runs-on: ubuntu-latest
  
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        pytest --verbosity=2 --showlocals
        
 second_j:
  name: send_art
  needs: first_j
  runs-on: ubuntu-latest
  
  steps:
   - name: Create artifact data
     run: echo "All tests are sucsess" > ${{ env.path }}${{ env.artifact_body.txt }}
   - name: Save Artifact
     uses: actions/upload-artifact@v3
     with:
      name: ${{ env.artifact_name }}
      path: ${{ env.path }}${{ env.artifact_body.txt }}
  
